name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=20.3.3
  - hydra-core=1.0.6
  - python=3.8
  - mlflow=2.2.2
  - pip:
      - wandb==0.10.21
      - protobuf==3.20.0
      - hydra-joblib-launcher==1.1.2
